version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-174-129-227-205.compute-1.amazonaws.com
            database: d7u8gopkateslr
            schema: public
            user: wxghhqvxkkjnnc
            password: a5fd0bf80e3e8f2dcf0fd616683436bfe77561c68a27725e61c98a63d3d80fce
            ssl: true
            rawAccess: false
            port: '5432'
            migrations: true